---
title: "Zip downloads"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  github_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

## Purpose

Analyze download logs of zip files for 2017-06-09 Databrary Advisory Board meeting.

## Preliminaries

```{r}
zipdown <- read.csv("analysis/csv/databrary-zip-downloads.csv")
str(zipdown)
```

## Table of downloads by volume

```{r downloads-shared-greater-than-5-table}
zipdown %>% 
  filter(shared == "yes") %>%
  group_by(vol.name, vol.id) %>% 
  summarise(n.downloads = sum(downloads)) %>%
  arrange(desc(n.downloads)) %>%
  knitr::kable()
```

## Bar plot

```{r downloads-shared-greater-than-5}
zipdown %>%
  filter(shared == "yes") %>%
  group_by(vol.name, vol.id) %>% 
  summarise(n.downloads = sum(downloads)) %>%
  filter(n.downloads >= 5) %>%
  arrange(desc(n.downloads)) ->
  downloads.gt5

downloads.gt5 %>%
  ggplot() +
    aes(x=n.downloads) +
    geom_histogram()
```

```{r total-downloads-shared}
zipdown %>%
  filter(shared == "yes") %>%
  summarise(n.downloads = sum(downloads)) ->
  total.shared.downloads
```

There were `r total.shared.downloads` downloads of shared volumes from 2015-07-15 to 2017-06-08.