# Weekly

These data are collected and reported on roughly a weekly basis.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)

library(tidyverse)

databraryr::login_db(Sys.getenv("DATABRARY_LOGIN"), store = TRUE)

# Graphic theme elements
ln_size <- 3
base_size <- 14
color_orange <- "#ec7751"
color_teal <- "#4CAE99"
color_purple <- "#AB00FF"

databrary_theme <-
  ggplot2::theme_classic(base_size = base_size) +
  ggplot2::theme(axis.title.x = ggplot2::element_blank()) +
  ggplot2::theme(
    legend.position = "none",
    axis.text = ggplot2::element_text(size = ggplot2::rel(0.8),
                                      colour = "black")
  ) +
  ggplot2::theme(axis.line = ggplot2::element_blank()) +
  ggplot2::theme(plot.title = ggplot2::element_text(hjust = 0.5))
```

## Institutions & Authorized Users {-}

```{r}
# targets::tar_load(inst_invest_csv, store = '../_targets/')
# updated_stats <- inst_invest_csv
targets::tar_load(inst_invest_df, store = '../_targets/')
updated_stats <- inst_invest_df
```

```{r}
# Calculate change
n_rows <- dim(updated_stats)[1]

delta_investigators <- updated_stats$investigators[n_rows] - updated_stats$investigators[n_rows - 1]

delta_institutions <- updated_stats$institutions[n_rows] - updated_stats$institutions[n_rows - 1]
 
# filter NAs
updated_stats <- updated_stats %>%
  dplyr::filter(., !is.na(affiliates),
         !is.na(investigators),
         !is.na(affiliates),
         !is.na(date))
```

<!-- Now, we plot the data. -->

```{r fig-databrary-inst-invest-timeseries, fig.cap="Change over time in authorized investigators and authorizing institutions"}
# Create a tidy form for plotting both institutions and investigators and affiliates
gathered_stats <- updated_stats %>%
  tidyr::gather(., key = "type", value = "count",-date) %>%
  dplyr::mutate(date = lubridate::as_date(date)) %>%
  dplyr::select(date, count, type) %>%
  dplyr::filter(type %in% c('institutions', 'investigators')) %>%
  dplyr::filter(!is.na(count))

# Plot
users_plot <- gathered_stats %>%
  ggplot(., aes(
    x = date,
    y = count,
    color = type,
    group = type
  )) +
  scale_x_date(date_labels = "%Y", date_breaks = '1 year') +
  geom_point() +
  geom_line(linewidth = ln_size) +
  scale_colour_manual(values = c(color_orange, color_teal)) +
  ggtitle(paste("Authorizations as of ", Sys.Date())) +
  ylab("Authorizations") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, plyr::round_any(max(
    gathered_stats$count
  ), 100, ceiling), 100),
  expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, plyr::round_any(max(
    gathered_stats$count
  ), 100, ceiling)))

cowplot::ggdraw(users_plot) +
  cowplot::draw_label(
    paste0(
      "Investigators: ",
      updated_stats$investigators[n_rows],
      " (+ ",
      delta_investigators,
      ")"
    ),
    colour = color_teal,
    .6,
    .8
  ) +
  cowplot::draw_label(
    paste0(
      "Institutions: ",
      updated_stats$institutions[n_rows],
      " (+ ",
      delta_institutions,
      ")"
    ),
    colour = color_orange,
    .75,
    .5
  )
```

### New Institutions {-}

```{r db-inst-table}
new_institutions <- databraryr::get_db_stats(type = "institutions")
if (!is.null(new_institutions)) {
  new_institutions %>%
    dplyr::mutate(db_url = paste0("https://databrary.org/party/", id)) %>%
    dplyr::select(., sortname, db_url) %>%
    knitr::kable(col.names = c("Institution Name", "Databrary URL"), "html") %>%
    kableExtra::kable_styling(.) #%>%
  
} else {
  cat("No new institutions since last report.")
}
```

### New and Updated Authorized Investigators {-}

```{r db-people-table}
new_people <- databraryr::get_db_stats(type = "people")
if (!is.null(new_people)) {
  new_people %>%
    dplyr::mutate(db_url = paste0("https://databrary.org/party/", id)) %>%
    dplyr::select(., sortname, prename, affiliation, db_url) %>%
    tidyr::unite(col = "Investigator Name", prename, sortname, sep = " ") %>%
    knitr::kable(col.names = c("Full Name", "Affiliation",
                               "Databrary URL"),
                 "html") %>%
    kableExtra::kable_styling(.) #%>%
} else {
  cat("No new investigators since last report.")
}
```

## Volumes {-}

```{r get-new-db-stats}
new_stats <- databraryr::get_db_stats()
new_stats$date <- lubridate::as_datetime(new_stats$date)
```

```{r, load-volumes-data}
if (params$from_gs) {
} else {
  old_vols <- readr::read_csv("csv/volumes-shared-unshared.csv", show_col_types = FALSE)
}

if (purrr::is_empty(old_vols)) {
  stop("No old data loaded.")
}
```

```{r update-volumes-data}
# Filter NAs
updated_vols <- old_vols %>%
  dplyr::filter(., !is.na(shared_volumes),
                !is.na(unshared_volumes),
                !is.na(date))  

if (as.logical(params$update_stats)) {
  next_entry <- dim(updated_vols)[1] + 1
  updated_vols[next_entry,] = NA
  
  updated_vols$date[next_entry] <- new_stats$date
  if (is.null(new_stats$datasets_shared)) {
    new_stats$datasets_shared = 0
  }
  updated_vols$shared_volumes[next_entry] <- new_stats$datasets_shared
  updated_vols$unshared_volumes[next_entry] <- 
    new_stats$datasets_total - new_stats$datasets_shared
}


# Calculate change
n_rows <- dim(updated_vols)[1]

delta_shared <- updated_vols$shared_volumes[n_rows] - updated_vols$shared_volumes[n_rows - 1]

delta_unshared <- updated_vols$unshared_volumes[n_rows] - updated_vols$unshared_volumes[n_rows - 1]

updated_vols <- updated_vols %>%
  dplyr::filter(., !is.na(shared_volumes),
                !is.na(unshared_volumes),
                !is.na(date))

gathered_vols <- updated_vols %>%
  tidyr::gather(., key = "type", value = "count", -date)
```

```{r db-vols-plot, fig.cap="Change in shared and unshared volumes over time."}
# Plot
vols_plot <- gathered_vols %>%
  ggplot(., aes(
    x = date,
    y = count,
    color = type,
    group = type
  )) +
  geom_point() +
  geom_line(size = ln_size) +
  scale_colour_manual(values = c(color_orange, color_teal)) +
  ggtitle(paste("Volumes as of ", Sys.Date())) +
  ylab("Volumes") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, plyr::round_any(max(
    gathered_vols$count
  ),
  100, ceiling), 100),
  expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, plyr::round_any(max(
    gathered_vols$count
  ),
  100, ceiling)))

cowplot::ggdraw(vols_plot) +
  cowplot::draw_label(
    paste0(
      "Unshared: ",
      updated_vols$unshared_volumes[n_rows],
      " (+",
      delta_unshared,
      ")"
    ),
    colour = color_teal,
    .75,
    .50
  ) +
  cowplot::draw_label(
    paste0(
      "Shared: ",
      updated_vols$shared_volumes[n_rows],
      " (+",
      delta_shared,
      ")"
    ),
    colour = color_orange,
    .6,
    .85
  )
```


```{r update-vols-shared-unshared-gs}
if (as.logical(params$update_gs)) {
  db <- db %>%
    gs_add_row(ws = 'volumes-shared-unshared', input = updated_vols)
} else {
  message("'update_gs' parameter is 'false', so Google Sheet data unmodified.")
}
```

```{r update-vols-shared-unshared-csv}
if (as.logical(params$update_csv)) {
  if (!is_empty(updated_vols)) {
    readr::write_csv(updated_vols, "csv/volumes-shared-unshared.csv")
    message("Updated 'csv/volumes-shared-unshared.csv'.")    
  } else {
    message("No new volumes data to write.")
  }
}
```

## New volumes {-}

```{r new-volumes}
# define helper functions
new_volumes <- databraryr::get_db_stats(type = "datasets")
if (is.null(new_volumes)) {
  stop('New volumes data not downloaded.')
}
```


```{r}
unnested_vols <- new_volumes %>%
  dplyr::rename(vol_id = id, vol_name = name) %>%
  tidyr::unnest(., cols = c(owners))
```

```{r}
unnested_vols <- unnested_vols %>%
  dplyr::mutate(
    .,
    url = paste0("https://nyu.databrary.org/volume/", vol_id),
    date_created = lubridate::as_date(creation)
  )
```

```{r}
unnested_vols %>%
  dplyr::select(., vol_name, date_created, owners, url) %>%
  knitr::kable(col.names = c("Volume Name", "Date Created", "Owner Name", "Databrary URL"), "html") %>%
  kableExtra::kable_styling(.)
```

## Citations {-}

```{r}
if (params$from_gs) {
} else {
  old_citations <- readr::read_csv("csv/citations-monthly.csv", show_col_types = FALSE)
}

old_citations <- old_citations %>%
  dplyr::mutate(date = lubridate::as_date(date))
```

```{r get-new-citations}
# Get citation counts from Google Scholar
get_citation_stats <- function(project = 'databrary') {
  if (project %in% c('databrary', 'Databrary')) {
    url <-
      'https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22databrary%22+%22Databrary%22&btnG='
  } else if (project %in% c('datavyu', 'Datavyu')) {
    url <-
      'https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22Datavyu%22+%22datavyu%22&btnG='
  }
  
  r <- httr::GET(url = url)
  if (httr::status_code(r) == 200) {
    content <- httr::content(r, 'text')
  } else {
    message(paste0('Download Failed, HTTP status ', httr::status_code(r)))
  }
  
  n_results <-
    stringr::str_match(content, pattern = "About ([0-9]+)")[2]
  if (is.null(n_results)) {
    message(paste0('Unable to parse results from search.'))
    return(NULL)
  } else {
    return(as.numeric(n_results))
  }
}

databrary_cites <- get_citation_stats('databrary')
datavyu_cites <- get_citation_stats('datavyu')
```

```{r}
# Merge old with new
citations <- old_citations
if (as.logical(params$update_stats)) {
  next_value <- dim(old_citations)[1] + 1
  citations[next_value, ] <- NA
  
  citations$date[next_value] <- lubridate::as_date(Sys.Date())
  citations$databrary_citations[next_value] <- databrary_cites
  citations$datavyu_citations[next_value] <- datavyu_cites
}

# Calculate change
n_rows <- dim(citations)[1]
delta_db_cites <-
  citations$databrary_citations[n_rows] - citations$databrary_citations[n_rows - 1]
delta_dv_cites <-
  citations$datavyu_citations[n_rows] - citations$datavyu_citations[n_rows - 1]

# Filter NAs
citations <- citations %>%
  dplyr::filter(.,!is.na(date),
                !is.na(databrary_citations),
                !is.na(datavyu_citations))
```


```{r db-dv-citations-plot, fig.cap="Change in citations of Databrary and Datavyu over time"}
gathered_citations <- citations %>%
  tidyr::gather(., key = "type", value = "count", -date)

# Plot
citations_plot <-
  gathered_citations %>%
  ggplot(., aes(
    x = date,
    y = count,
    color = type,
    group = type
  )) +
  geom_point() +
  geom_line(size = ln_size) +
  scale_colour_manual(values = c(color_orange, color_teal)) +
  ggtitle(paste("Citations as of ", Sys.Date())) +
  ylab("Citations") +
  databrary_theme +
  scale_y_continuous(breaks = seq(0, plyr::round_any(
    max(gathered_citations$count),
    100, ceiling
  ), 100),
  expand = c(0, 0)) +
  coord_cartesian(ylim = c(0, plyr::round_any(
    max(gathered_citations$count), 100, ceiling
  )))

cowplot::ggdraw(citations_plot) +
  cowplot::draw_label(
    paste0(
      "Datavyu: ",
      citations$datavyu_citations[n_rows],
      " (+",
      delta_dv_cites,
      ")"
    ),
    colour = color_teal,
    .86,
    .3
  ) +
  cowplot::draw_label(
    paste0(
      "Databrary: ",
      citations$databrary_citations[n_rows],
      " (+",
      delta_db_cites,
      ")"
    ),
    colour = color_orange,
    .7,
    .7
  )
```

Google Scholar Citations for  [Databrary](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C39&q=%22databrary%22+%22Databrary%22&oq=) and [Datavyu](https://scholar.google.com/scholar?hl=en&as_sdt=1%2C39&as_vis=1&q=%22Datavyu%22+%22datavyu%22&btnG=).

```{r update-citations-gs}
if (as.logical(params$update_gs)) {
  # new_data <- citations$date[next_value,]
  # db <- db %>%
  #   googlesheets::gs_add_row(ws = 'citations-monthly', 
  #                            input = new_data)
  # message("'update_gs' parameter is 'TRUE', so Google Sheet data will be updated.")
} else {
  message("'update_gs' parameter is 'FALSE', so Google Sheet data unmodified.")
}
```

```{r update-citations-csv}
if (as.logical(params$update_csv)) {
  if (!(is_empty(citations))) {
    readr::write_csv(citations, "csv/citations-monthly.csv")
    message("Updated 'csv/citations-monthly.csv'.")    
  } else {
    message("No new citations data to write.")
  }
}
```

<!-- ## Archived reports {-} -->

<!-- ```{r child = 'rmd/old_weekly_reports.Rmd'} -->
<!-- ``` -->

